name: Test

# Default to 'contents: read', which grants actions to read commits.
#
# If any permission is set, any permission not included in the list is
# implicitly set to "none".
#
# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.module }} / ${{ matrix.platform }} / ${{ matrix.go-version || 'minimum' }}
    strategy:
      fail-fast: false
      matrix:
        module:
          - atomicwriter
          - capability
          - mount
          - mountinfo
          - reexec
          - sequential
          - signal
          - symlink
          - user
          - userns
        go-version:
          - "" # do not specify go-version to fall back on go-version-file (use go.mod); see https://github.com/actions/setup-go/issues/450#issuecomment-3620402646
          - oldstable
          - stable
        platform: [ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025, macos-15, macos-26]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10 # guardrails timeout for the whole job

    env:
      GOTOOLCHAIN: local
      PACKAGES: ${{ matrix.module }}

    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
        go-version-file: ./${{ matrix.module }}/go.mod # used when go-version is not specified.
        # Disable caching as we don't have top-level go.sum needed for
        # the cache key, and specifying multiple go.sums is not trivial
        # (see https://github.com/moby/sys/pull/160 for details).
        cache: false
    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.10
        # We don't need to run golangci-lint here yet, but
        # there's no way to avoid it, so run it on one module.
        working-directory: ./${{ matrix.module }}

    - name: go mod tidy
      run: |
        make foreach CMD="go mod tidy"
        git diff --exit-code
    - name: go fix
      run: |
        make foreach CMD="go fix"
        git diff --exit-code
    - name: Lint
      run: make lint
    - name: Cross build
      if: ${{ runner.os == 'Linux' }}
      run: make cross
    - name: Test
      run: |
        uname -a
        make test
    - name: Send to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # used to upload coverage reports: https://github.com/moby/buildkit/pull/4660#issue-2142122533

  codespell:
    runs-on: ubuntu-24.04
    timeout-minutes: 10 # guardrails timeout for the whole job
    steps:
    - uses: actions/checkout@v6
    - run: pip install --break-system-packages codespell==v2.3.0
    - run: codespell
